version: "3"
services:
  challenge-charlie:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_OPEN_WEATHER_KEY=772920597e4ec8f00de8d376dfb3f094
      - REACT_APP_OPEN_CAGE_KEY=c63386b4f77e46de817bdf94f552cddf
